# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Component:
    DESCRIPTION = "Create an issue comment"


class Input:
    BODY = "body"
    ORGANIZATION = "organization"
    REPOSITORY = "repository"
    ISSUE_NUMBER = "issue_number"
    

class Output:
    URL = "url"
    

class CreateCommentInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "body": {
      "type": "string",
      "title": "Body",
      "description": "Body text of issue comment",
      "order": 1
    },
    "organization": {
      "type": "string",
      "title": "Organization",
      "description": "Organizational owner of repository",
      "order": 3
    },
    "repository": {
      "type": "string",
      "title": "Repository",
      "description": "Repository to post issue comment",
      "order": 2
    },
    "issue_number": {
      "type": "number",
      "title": "ISSUE NUMBER",
      "description": "Issue number",
      "order": 4
    }
  },
  "required": [
    "body",
    "repository",
    "issue_number"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class CreateCommentOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "url": {
      "type": "string",
      "title": "URL",
      "description": "URL",
      "order": 1
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
